apiVersion: v1
kind: Service
metadata:
 name: es
 labels:
  service: elasticsearch
spec:
 type: LoadBalancer
 ports:
 - port: 9200
   name: serving
 - port: 9300
   name: node-to-node
 selector:
  service: elasticsearch
status:
  loadBalancer: {}